name: Release

# 此工作流用于在 dev 分支的推送时创建发布 PR 或发布到 npm（使用 Changesets）。
# 环境变量和密钥由 secrets 提供。此处仅为中文注释说明。

on:
  push:
    branches:
      - dev

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.UPDATE_TEMPLATE_SSH_KEY }}

      - uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_TEMPLATE_SSH_KEY }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
